### ISSUE TITLE
System segfaulted

### ISSUE THREAD

**Issue by jnfmac** [davidfornas/videre_stereo_cam#2]
Hello: I was trying to run: $roslaunch videre_stereo_cam videre_non_stoc.launch 
and received the following output
# SUMMARY

PARAMETERS
- /rosdistro: indigo
- /rosversion: 1.11.13
- /stereo/videre_stereo_cam/brightness_auto: True
- /stereo/videre_stereo_cam/convert_to_color: False
- /stereo/videre_stereo_cam/exposure_auto: True
- /stereo/videre_stereo_cam/fps: 30.0
- /stereo/videre_stereo_cam/frame_id: stereo
- /stereo/videre_stereo_cam/gain_auto: True
- /stereo/videre_stereo_cam/videre_mode: none

NODES
  /stereo/
    videre_stereo_cam (videre_stereo_cam/videre_stereo_node)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[stereo/videre_stereo_cam-1]: started with pid [21433]
System segfaulted, stopping camera nicely
[stereo/videre_stereo_cam-1] process has died [pid 21433, exit code -11, cmd /home/arai/workspace/devel/lib/videre_stereo_cam/videre_stereo_node __name:=videre_stereo_cam __log:=/home/arai/.ros/log/5f3e7782-1b75-11e5-9285-a088b4350fa0/stereo-videre_stereo_cam-1.log].
log file: /home/arai/.ros/log/5f3e7782-1b75-11e5-9285-a088b4350fa0/stereo-videre_stereo_cam-1*.log
[stereo/videre_stereo_cam-1] restarting process
process[stereo/videre_stereo_cam-1]: started with pid [21490]
System segfaulted, stopping camera nicely

and this keeps on repeating. Am I missing something? I'm using the Videre stereo camera model: STH-DCSG-STOC-C.

**Comment by davidfornas** [comment]
I usually have this problem when the camera is not properly started. Is the red led on? Which kind of FireWire board/device are you using? Which connector? You should use 6 pin connectors in both sides as 4 pin connector does not provide power.

If you have it all right it can also be our fault as this package has only tested under Hydro at most. Can you easily try it over Hydro?

**Comment by jnfmac** [comment]
No the red led isn't on. I'm testing it under Indigo on my laptop and it was lacking a FireWire board so we bought a FireWire to USB adapter. 

I had a feeling that might've been the cause of the camera not working after doing research and reading reviews/forum posts about FireWire to USB adapters not working very well. I'm currently looking into getting an express card slot that plugs into a USB port and a FireWire adapter that plugs into an express card slot and trying that out. I'll update if it works, if not I might just need to do the work on a desktop.

**Comment by davidfornas** [comment]
Indeed the Camera is off. I am using a PCI card and it works fine. I don't know if there is an adapter that provide power as well.
